### ISSUE TITLE
APEX folder is removed?

### ISSUE THREAD

**Issue by otherexception** [MaksymBilenko/docker-oracle-apex#1]
I see on your script:
rm -rf /u01/app/oracle/apex
What is your purpose? Where is new apex folder?

**Comment by MaksymBilenko** [comment]
@otherexception It's not needed after upgrade

**Comment by MaksymBilenko** [comment]
@otherexception Do you have some concerns?

**Comment by otherexception** [comment]
I can't find apex images virtual folder? Where are all files (themes/plugins - js,css)? 
Until now I used apex 4.2 and those files were in  /u01/app/oracle/apex/images by default

**Comment by MaksymBilenko** [comment]
@otherexception just upgrade and report an issues if any presents

**Comment by otherexception** [comment]
I upgraded and everything works fine. I have only problem with #APP_IMAGES# directory. Before upgrade that refers to path /u01/app/oracle/apex/images. After upgrade all files were removed and i don't know where I should copy these files from backup now.

**Comment by MaksymBilenko** [comment]
You don't need to copy anything
