### ISSUE TITLE
DB_CONTAINER_NAME - 

### ISSUE THREAD

**Issue by josvaler** [MaksymBilenko/docker-oracle-apex#2]
**Doc enhacement

I would like to recommend setting the DB_CONTAINER_NAME before running the upgrade command.  

Apex upgrade up to v 5.*

1. docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                                            NAMES
9ca7d640fb9e        sath89/oracle-12c   "/entrypoint.sh "   About an hour ago   Up About an hour    0.0.0.0:1521->1521/tcp, 0.0.0.0:8080->8080/tcp   **dreamy_babbage**

2. export DB_CONTAINER_NAME=**dreamy_babbage** --> Replace with your container name 
                                                                                      --> Depending on your env and shell it could be different, export is valid for bash in this case.

Making this you can avoid rare docker messages.

Good work and thanks a lot.

-José Valerio

**Comment by MaksymBilenko** [comment]
@josvaler I don't really see why do you need this? anyways you would need to use link.

**Comment by josvaler** [comment]
This happened to me with docker running on Mac
