### ISSUE TITLE
Error during Upgrade

### ISSUE THREAD

**Issue by Ph1975** [MaksymBilenko/docker-oracle-apex#3]
Hi,

when using the command:
`docker run -it --rm --volumes-from 32b130da6042 --link 32b130da6042:oracle-database sath89/apex install`

i get following output:
Archive:  /tmp/instantclient-basic-linux.x64-12.1.0.2.0.zip
  inflating: /instantclient_12_1/adrci
  inflating: /instantclient_12_1/BASIC_README
  inflating: /instantclient_12_1/genezi
  inflating: /instantclient_12_1/libclntshcore.so.12.1
  inflating: /instantclient_12_1/libclntsh.so.12.1
  inflating: /instantclient_12_1/libipc1.so
  inflating: /instantclient_12_1/libmql1.so
  inflating: /instantclient_12_1/libnnz12.so
  inflating: /instantclient_12_1/libocci.so.12.1
  inflating: /instantclient_12_1/libociei.so
  inflating: /instantclient_12_1/libocijdbc12.so
  inflating: /instantclient_12_1/libons.so
  inflating: /instantclient_12_1/liboramysql12.so
  inflating: /instantclient_12_1/ojdbc6.jar
  inflating: /instantclient_12_1/ojdbc7.jar
  inflating: /instantclient_12_1/uidrvci
  inflating: /instantclient_12_1/xstreams.jar
Archive:  /tmp/instantclient-sqlplus-linux.x64-12.1.0.2.0.zip
  inflating: /instantclient_12_1/glogin.sql
  inflating: /instantclient_12_1/libsqlplusic.so
  inflating: /instantclient_12_1/libsqlplus.so
  inflating: /instantclient_12_1/sqlplus
  inflating: /instantclient_12_1/SQLPLUS_README
Database Connetion is OK
ls: cannot access /u01/app/oracle: No such file or directory
Failed to find database files, run example:
 docker run -it --rm --volumes-from :oracle-database --link :oracle-database sath89/apex install

When starting bash in the container, the path is available:
drwxr-xr-x 1 oracle dba  4096 Dec 12 21:12 .
drwxr-xr-x 1 root   root 4096 Nov 27  2015 ..
drwxr-x--- 3 oracle dba  4096 Dec 12 20:55 admin
drwxr-x--- 3 oracle dba  4096 Dec 12 21:01 audit
drwxr-x--- 3 oracle dba  4096 Dec 12 20:54 cfgtoollogs
drwxr-x--- 2 oracle dba  4096 Dec 12 21:12 checkpoints
drwxr-xr-x 2 oracle dba  4096 Dec 12 21:12 dbs
drwxrwxr-x 4 oracle dba  4096 Dec 12 20:55 diag
drwxr-x--- 4 oracle dba  4096 Dec 12 20:55 fast_recovery_area
drwxr-x--- 3 oracle dba  4096 Dec 12 20:55 oradata
lrwxrwxrwx 1 root   root   23 Dec 12 20:53 product -> /u01/app/oracle-product
root@32b130da6042:/u01/app/oracle#

can you please advise?

**Comment by jdemovic** [comment]
Hi,
I have the same issue now.
Is there some solution ?
regards.
J

**Comment by MaksymBilenko** [comment]
Database should be started with volume. Seems like you have started oracle database without -v
