### ISSUE TITLE
sath89/apex is not available anymore

### ISSUE THREAD

**Issue by ka84** [MaksymBilenko/docker-oracle-apex#5]
$ docker login
Authenticating with existing credentials...
Login Succeeded

$ docker run -it --rm --volumes-from test_apex_12c --link test_apex_12c:oracle-database sath89/apex install
Unable to find image 'sath89/apex:latest' locally
docker: Error response from daemon: pull access denied for sath89/apex, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

**Comment by MaksymBilenko** [comment]
Moved to quay.io
